---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:9.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:9.1.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:8.1.4
codenotary:
  base_image: 4yury.m@gmail.com
  signer: 4yury.m@gmail.com
